name: Claude Code Workflow
on:
  push:
    branches: [ main ]
    paths:
      - 'meeting-notes.md'

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anthropic

      - name: Generate requirements
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python - <<EOF
          import anthropic
          import os

          client = anthropic.Anthropic(api_key=os.environ['ANTHROPIC_API_KEY'])

          with open('meeting-notes.md', 'r') as f:
              meeting_notes = f.read()

          prompt = f"""以下の議事録を基に要件定義ドキュメントを作成してください。
          以下のテンプレートに従い、箇条書きで整理してください。

          {meeting_notes}

          ## 要件定義
          ### プロジェクトの目的
          - 

          ### 機能要件
          - 

          ### 非機能要件
          - 

          ### 制約事項
          - 
          """

          response = client.messages.create(
              model="claude-3-sonnet-20240229",
              max_tokens=4000,
              messages=[{"role": "user", "content": prompt}]
          )

          with open('requirements.md', 'w') as f:
              f.write(response.content[0].text)
          EOF

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add requirements.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: 要件定義を更新" && git push)